<template>
  <div class="loadingio-spinner-bean-eater-z0ia6k7gmvr"><div class="ldio-zd69hk64bj">
  <div><div></div><div></div><div></div></div><div><div></div><div></div><div></div></div>
  </div></div>
</template>

<style scoped>
@keyframes ldio-zd69hk64bj-1 {
    0% { transform: rotate(0deg) }
   50% { transform: rotate(-45deg) }
  100% { transform: rotate(0deg) }
}
@keyframes ldio-zd69hk64bj-2 {
    0% { transform: rotate(180deg) }
   50% { transform: rotate(225deg) }
  100% { transform: rotate(180deg) }
}
.ldio-zd69hk64bj > div:nth-child(2) {
  transform: translate(-15px,0);
}
.ldio-zd69hk64bj > div:nth-child(2) div {
  position: absolute;
  top: 30px;
  left: 30px;
  width: 90px;
  height: 45px;
  border-radius: 90px 90px 0 0;
  background: #f8b26a;
  animation: ldio-zd69hk64bj-1 1s linear infinite;
  transform-origin: 45px 45px
}
.ldio-zd69hk64bj > div:nth-child(2) div:nth-child(2) {
  animation: ldio-zd69hk64bj-2 1s linear infinite
}
.ldio-zd69hk64bj > div:nth-child(2) div:nth-child(3) {
  transform: rotate(-90deg);
  animation: none;
}@keyframes ldio-zd69hk64bj-3 {
    0% { transform: translate(142.5px,0); opacity: 0 }
   20% { opacity: 1 }
  100% { transform: translate(52.5px,0); opacity: 1 }
}
.ldio-zd69hk64bj > div:nth-child(1) {
  display: block;
}
.ldio-zd69hk64bj > div:nth-child(1) div {
  position: absolute;
  top: 69px;
  left: -6px;
  width: 12px;
  height: 12px;
  border-radius: 50%;
  background: #80bdff;
  animation: ldio-zd69hk64bj-3 1s linear infinite
}
.ldio-zd69hk64bj > div:nth-child(1) div:nth-child(1) { animation-delay: -0.67s }
.ldio-zd69hk64bj > div:nth-child(1) div:nth-child(2) { animation-delay: -0.33s }
.ldio-zd69hk64bj > div:nth-child(1) div:nth-child(3) { animation-delay: 0s }
.loadingio-spinner-bean-eater-z0ia6k7gmvr {
  width: 150px;
  height: 150px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-zd69hk64bj {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-zd69hk64bj div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>